
name: Python application
on:
  push:
    branches:
      - main
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    env:
      OUTPUT_SUFFIX: MySuffix
    steps:
      - name: Use environment variables from entire job
        run: echo We display the $OUTPUT_SUFFIX define for the entire job1

      - name: Use environment variables from entire job
        run: echo We reuse the output suffix $OUTPUT_SUFFIX multiples time in the entire job1
      
