
name: Python application
on:
  push:
    branches:
      - main
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Use environment variables from entire job
        run: echo ${{secrets.AWS_ACCESS_KEY_ID}}
      
